---
image: node:10.15-alpine

cache:
  paths:
    - node_modules/

before_script:
  - npm config set unsafe-perm true
  - npm ci

stages:
  - lint
  - build
  - test
  - deploy

lint:
  stage: lint
  script:
    - npm run lint

build:
  stage: build
  script:
    - npm run build

test:
  stage: test
  script:
    - npm test

deploy:
  stage: deploy
  script:
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
    - npm run publish
  only:
    - master
