export enum ReservedChannels {
    application_login = "@desktop:application/login",
    application_login_auth = "@desktop:application/login-auth",
    application_open_url = "@desktop:application/open-url",
    application_second_instance = "@desktop:application/second-instance",
    window_blur = "@desktop:window/blur",
    window_center = "@desktop:window/center",
    window_close = "@desktop:window/close",
    window_flashFrame = "@desktop:window/flashFrame",
    window_focus = "@desktop:window/focus",
    window_getBounds = "@desktop:window/getBounds",
    window_getMinimumSize = "@desktop:window/getMinimumSize",
    window_hide = "@desktop:window/hide",
    window_maximize = "@desktop:window/maximize",
    window_minimize = "@desktop:window/minimize",
    window_moveTop = "@desktop:window/moveTop",
    window_reload = "@desktop:window/reload",
    window_restore = "@desktop:window/restore",
    window_setFullScreen = "@desktop:window/setFullScreen",
    window_show = "@desktop:window/show",
}
