export enum ReservedChannels {
    application_login = "@desktop:application/login",
    application_loginAuth = "@desktop:application/loginAuth",
    application_openUrl = "@desktop:application/openUrl",
    application_secondInstance = "@desktop:application/secondInstance",
    globalShortcut_invoked = "@desktop:globalShortcut/invoked",
    globalShortcut_isRegistered = "@desktop:globalShortcut/isRegistered",
    globalShortcut_register = "@desktop:globalShortcut/register",
    globalShortcut_unregister = "@desktop:globalShortcut/unregister",
    globalShortcut_unregisterAll = "@desktop:globalShortcut/unregisterAll",
    window_blur = "@desktop:window/blur",
    window_center = "@desktop:window/center",
    window_close = "@desktop:window/close",
    window_flashFrame = "@desktop:window/flashFrame",
    window_focus = "@desktop:window/focus",
    window_getBounds = "@desktop:window/getBounds",
    window_getMinimumSize = "@desktop:window/getMinimumSize",
    window_hide = "@desktop:window/hide",
    window_maximize = "@desktop:window/maximize",
    window_minimize = "@desktop:window/minimize",
    window_moveTop = "@desktop:window/moveTop",
    window_reload = "@desktop:window/reload",
    window_restore = "@desktop:window/restore",
    window_setFullScreen = "@desktop:window/setFullScreen",
    window_show = "@desktop:window/show",
}
