---
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          name: restore-packages
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: lint
          command: npm run lint

      - run:
          name: build
          command: npm run build

      - run:
          name: test
          command: npm test

  build-coverage:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          name: restore-packages
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: test
          command: npm test

      - run:
          name: coverage
          command: |
            sudo npm install -g --silent codecov
            codecov -f packages/*/coverage/*.json

  build-analyze:
    docker:
      - image: circleci/node:10.15
    steps:
      - run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash

      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          name: restore-packages
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: build
          command: npm run build

      - run:
          name: fossa
          command: fossa

  deploy:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          name: restore-packages
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
            npm run publish

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - build-coverage
      - build-analyze:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
