---
name: Package
on:
  release:
    types:
      - published
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [12.x]
        include:
          - os: ubuntu-latest
            platform: linux
            installer: desktop_${GITHUB_REF##*/v}_amd64.deb
          - os: windows-latest
            platform: win32
            installer: desktop-${GITHUB_REF##*/v}-win32-x64-setup.zip
          - os: macOS-latest
            platform: darwin
            installer: desktop-${GITHUB_REF##*/v}.dmg
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install npm dependencies
        run: |
          npm ci
      - name: Build
        run: |
          npm run build
      - name: Build asar
        run: |
          npm run asar
      - name: npm package
        run: |
          npm run package:${{ matrix.platform }}
      - name: "Get upload_url"
        run: echo "::set-output name=upload_url::https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)/assets{?name,label}"  
        id: release
      - name: Upload Package Zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: packages/desktop/pack/desktop-${GITHUB_REF##*/v}-${{ matrix.platform }}.zip
          asset_name: desktop-${GITHUB_REF##*/v}-${{ matrix.platform }}.zip
          asset_content_type: application/zip
      - name: Upload Package Installer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: packages/desktop/pack/${{ matrix.installer }}
          asset_name: ${{ matrix.installer }}
          asset_content_type: application/octet-stream
