---
name: Package
on:
  release:
    types:
      - published
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [12.x]
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64
            installer-prefix: desktop_
            installer-postfix: _amd64.deb
          - os: windows-latest
            platform: win32
            arch: x64
            installer-prefix: desktop-
            installer-postfix: -win32-x64-setup.zip
          - os: macOS-latest
            platform: darwin
            arch: x64
            installer-prefix: desktop-
            installer-postfix: .dmg
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install npm dependencies
        run: |
          npm ci
      - name: Build
        run: |
          npm run build
      - name: Build asar
        run: |
          npm run asar
      - name: Build packages
        run: |
          npm run package:${{ matrix.platform }}
      - name: Get upload_url
        run: echo "::set-output name=upload_url::https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)/assets{?name,label}"  
        id: release
      - name: Get version
        run: echo "::set-output name=version::${GITHUB_REF##*/v}"
        id: version
      - name: Get zip file
        run: echo "::set-output name=filename::desktop-${{ steps.version.outputs.version }}-${{ matrix.platform }}-${{ matrix.arch }}.zip"
        id: zip
      - name: Get installer file
        run: echo "::set-output name=filename::${{ matrix.installer-prefix }}${{ steps.version.outputs.version }}${{ matrix.installer-postfix }}"
        id: installer
      - name: Upload Package Zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: packages/desktop/pack/${{ steps.zip.outputs.filename }}
          asset_name: ${{ steps.zip.outputs.filename }}
          asset_content_type: application/zip
      - name: Upload Package Installer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: packages/desktop/pack/${{ steps.installer.outputs.filename }}
          asset_name: ${{ steps.installer.outputs.filename }}
          asset_content_type: application/octet-stream
