---
name: Package

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [10.x]
        include:
          - os: ubuntu-latest
            plafform: linux
          - os: windows-latest
            platform: win32
          - os: macOS-latest
            platform: darwin

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci, build, and test
        run: |
          npm ci
          npm run build
          npm run pack
          npm run package:${{ matrix.platform }}
